config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 10 }
  EMAIL_RJEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true,length: { maximum: 105 }, format: { with: EMAIL_RJEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(set_params)
    @article.user = User.first

    if @article.save
      flash[:notice] = "Article was save successfully."
      redirect_to @article
    else
      render :new, status: 422
    end
  end

  def edit
  end

  def update
    if @article.update(set_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit', status: 422
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors" %>
      <%= form_with(model: @article, class: "shadow p-4 mt-4 mb-5 bg-info rounded", local: true) do |f| %>
        <div class="form-group row mb-4">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of Article"  %>
          </div>
        </div>

        <div class="form-group row mb-4">
          <%= f.label :description, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of Article"  %>
          </div>
        </div>

        <div class="form-group justify-content-center">
          <center>
            <%= f.submit class: "btn btn-outline-light btn-lg" %>
          </center>
        </div>
      <% end %>
    </div>
    <center><%= link_to '[ Return to Articles listing Page ]', articles_path %></center>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">List all Articles </h1>

<div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-3 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= article.user.username if article.user %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article, class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article, class:"btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class:"btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %> </h1>

<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= @article.user.username if @article.user %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-info" %>
            <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, message| %>
    <div class="container">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    </div>
  <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is about page</h1>

<%= link_to 'Home Page', root_path %> |
<%= link_to 'Article listing page', articles_path %>

app/views/pages/home.html.erb
<div class="container text-center" id="container-home">
  <div class="mt-4 p-5 text-white rounded">
    <h1>Jumbotron Example</h1>
    <p>Lorem ipsum...</p>
    <button type="button" class="btn btn-success btn-lg">Sign Up</button>
  </div>
</div>
<footer class="fixed-bottom p-3 bg-dark text-center" id="sticky-footer">
    <span class="text-white">Copyright @ Your Website</span>
</footer>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>